config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :events, except: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos
  resources :events do
    resources :registrations, only: [:create]
  end

  get "about" => "pages#about"
  get "contact" => "pages#contact"

  namespace :api do
    resources :events
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  #
  # EVENT_CATEGORIES = ["Food and Drink", "Travel", "Running", "Book club", "Personal Development", "Coding meet-ups", "Watching Movies", "Language & Culture"]

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :photos
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  validates :name, presence: true, length: { maximum: 50 }
  validates :location, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :capacity, presence: true
  validate :ends_after_start
  validates :starts_at, :ends_at, presence: true
  validates :categories, presence: true#, inclusion: { in: EVENT_CATEGORIES }
  validates_inclusion_of :includes_food, :in => [true, false]
  validates_inclusion_of :includes_drinks, :in => [true, false]

  def ends_after_start
    return if ends_at.blank? || starts_at.blank?

    if ends_at < starts_at
      errors.add(:ends_at, :invalid, message: "date must be after the start date")
    end
  end

  def bargain?
    price < 30
  end

  def self.order_by_price
    order :price
  end

  def available?
    registrations.each do |registration|
      if set_status <= 0
        return false
      end
    end

    true
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  before_save :set_total_price

  def set_total_price
    total = self.event.price * guests_count
  end

  def set_status
    self.event.capacity =- guests_count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :registrated_events, through: :registrations, source: :event

  def full_name
    return profile.full_name if profile?

    email
  end

  def profile?
    profile.present? && profile.persisted?
  end

end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  def index
    render status:200, json: {
      events: Event.all
    }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event successfully created!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
      .require(:event)
      .permit(
        :name, :description, :location, :price, :capacity, :includes_food,
        :includes_drinks, :starts_at, :ends_at, :active, category_ids: []
      )
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:edit, :update]
    before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :bio)
      end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_event

  def create
    @registration = current_user.registrations.new(registration_params.merge({ event: @event }))
    @registration.set_total_price
    @registration.set_status
    @registration.save

    redirect_to @registration.event, notice: "Thank you for your registration!"
  end

  private

  def registration_params
    params.require(:registration).permit(:status, :guests_count, :total)
  end

  def load_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>

<div class="error-body">
  <%= render 'shared/validationerrors' %>
</div>

  <div class="form-group">
    <label>Event Name</label>
    <%= f.text_field :name, placeholder: "Event name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your event", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Location</label>
    <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "eg. 10.00", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label>Capacity</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :capacity, placeholder: "eg. 100", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label>Start Date:</label>
    <%= f.datetime_select :starts_at, prompt: "Select start date & time", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>End Date:</label>
    <%= f.datetime_select :ends_at, prompt: "Select end date & time", class: "form-control" %>
  </div>

  <hr/>
  <label>Amenities</label>

  <div class="form-group">
    <label>Food included: </label>
    <%= f.radio_button :includes_food, "0" %>
    <label for="includes_food_true"> YES </label>
    <%= f.radio_button :includes_food, "1" %>
    <label for="includes_food_false"> NO </label>
  </div>

  <div class="form-group">
    <label>Drinks included: </label>
    <%= f.radio_button :includes_drinks, "0" %>
    <label for="includes_drinks_true"> YES </label>
    <%= f.radio_button :includes_drinks, "1" %>
    <label for="includes_drinks_false"> NO </label>
  </div>
  <hr/>

  <div class="form-group">
    <label>Status</label> <br/>
    <%= f.check_box :active %> Published
  </div>
  <hr/>

  <div class="form-group">
    <label>Categories</label>

    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
      <div class="form-group">
        <%= b.check_box(class: "check_box") %> <%= b.object.name %>
      </div>
    <% end %>
  <hr/>

  <label>Photos</label>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <div class="form-group">
    <span class="btn btn-default">
      <span> Upload Photos </span>
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Registrations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
          <!-- add event.photo -->
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "VIEW", event, class: "btn btn-default" %>
            <%= link_to "UPDATE", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "+ CREATE NEW EVENT", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @event.name %>
    <p><%= @event.description %></p>
  </div>
  <hr/>

  <div class="panel-body">
    <!-- Registration Form -->
    <% if current_user != @event.user %>
      <%= render 'registrations/form' %>
    <% end %>
    <hr/>

    <!-- Main info -->
    <p>Location: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>
    <p>Start date: <%= @event.starts_at.strftime("%A, %B %e, %Y") %></p> <p><%= @event.starts_at.strftime("%l:%M %p") %></p>
    <p>End date: <%= @event.ends_at.strftime("%A, %B %e, %Y") %></p> <p><%= @event.ends_at.strftime("%l:%M %p") %></p>
    <br/>

    <p>Price: <%= @event.price %> <span>€</span> </p>
    <p>Capacity: <%= @event.capacity %> <%= @event.capacity > 1 ? "Guests" : "Guest" %></p>
    <br/>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="includes">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Drinks</del>").html_safe : "Drinks" %></li>
    </ul>
    <br/>

    <!-- Status -->
    <p>Status: <%= @event.active %> </p>
    <br/>

    <!-- Photos -->
    <h4>Photos</h4>
    <% @event.photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
    </div>
    <% end %>

    <!-- Categories -->
    <h4>Categories</h4>
    <% @categories.each do |category| %>
    <span class="label label-success"> <%= category.name %></span>
    <% end %>
  </div>

</div>
    <hr/>
<%= link_to "BACK", events_path, class: "btn btn-default" %>