config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :events, except: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos
  resources :events do
    resources :registrations, only: [:create]
  end

  get "about" => "pages#about"
  get "contact" => "pages#contact"

  namespace :api do
    resources :events
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  #
  # EVENT_CATEGORIES = ["Food and Drink", "Travel", "Running", "Book club", "Personal Development", "Coding meet-ups", "Watching Movies", "Language & Culture"]

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :photos
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user

  validates :name, presence: true, length: { maximum: 50 }
  validates :location, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :capacity, presence: true
  validate :ends_after_start
  validates :starts_at, :ends_at, presence: true
  validates :categories, presence: true#, inclusion: { in: EVENT_CATEGORIES }
  validates_inclusion_of :includes_food, :in => [true, false]
  validates_inclusion_of :includes_drinks, :in => [true, false]

  def ends_after_start
    return if ends_at.blank? || starts_at.blank?

    if ends_at < starts_at
      errors.add(:ends_at, :invalid, message: "date must be after the start date")
    end
  end

  def bargain?
    price < 30
  end

  def self.order_by_price
    order :price
  end

  def available?
    registrations.each do |registration|
      if set_status <= 0
        return false
      end
    end

    true
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  before_save :set_total_price

  def set_total_price
    total = self.event.price * guests_count
  end

  def set_status
    self.event.capacity =- guests_count
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :registrated_events, through: :registrations, source: :event

  def full_name
    return profile.full_name if profile?

    email
  end

  def profile?
    profile.present? && profile.persisted?
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event successfully created!"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
      .require(:event)
      .permit(
        :name, :description, :location, :price, :capacity, :includes_food,
        :includes_drinks, :starts_at, :ends_at, :active, category_ids: []
      )
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:edit, :update]
    before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :bio)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline|Bungee+Shade|Love+Ya+Like+A+Sister|Open+Sans|Passero+One" rel="stylesheet">

  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h3>This application was built in 2017</h3>

app/views/pages/contact.html.erb
<h2>Contact us </h2>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/assets/css/bootstrap.min.css" media="all" rel="stylesheet"/>
    <link rel="stylesheet" href="/assets/css/normalize.css">
    <title>CodaisseurUP</title>
  </head>

  <body>
    <section class="banner">
      <img src="https://media.giphy.com/media/3o7TKokImU6DXy3NV6/giphy.gif" alt="meet-up background image" />
      <h1>Your Events</h1>
      <%= link_to "VIEW YOUR EVENTS", events_path, class: "btn btn-default" %>

    </section>

    <hr/>
    <section class="events">
      <h2>Upcoming Events</h2>

    </section>

    <hr/>
    <section class="events">
      <h2>Find an event</h2>

    </section>

    <hr/>
    <section class="events">
      <h2>Explore</h2>

    </section>

    <footer>
      <p>&copy; 2018 CodaisseurUP</p>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">

        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.full_name %> <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><%= link_to "Your events", events_path %></li>
            <li role="separator" class="divider"></li>

            <% if current_user.profile? %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
            <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
            <% end %>
            <li><%= link_to "Edit Password", edit_user_registration_path %></li>

            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_validationerrors.html.erb
  <% @event.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>